package:
  name: rce_gen3_fw_lib
  version: {{ GIT_DESCRIBE_TAG }}

source:
   path: ..

build:
   number: {{ GIT_DESCRIBE_NUMBER|int }}
   noarch: python

requirements:

   host:
     - python
     - git
     - gitpython

   run:
     - python
     - rogue
     - numpy

about:
   home: https://github.com/slaclab/rce-gen3-fw-lib
   license: SLAC Open License
   license_file: LICENSE.txt
   summary: RCE Generation 3 Firmware Library

