# ----------------------------------------------------------------------------
# Title      : RCE Gen3 FW GitHub Actions CI Script
# ----------------------------------------------------------------------------
# This file is part of the 'RCE Gen3 Firmware library'. It is subject to
# the license terms in the LICENSE.txt file found in the top-level directory
# of this distribution and at:
#    https://confluence.slac.stanford.edu/display/ppareg/LICENSE.html.
# No part of the 'RCE Gen3 Firmware library', including this file, may be
# copied, modified, propagated, or distributed except according to the terms
# contained in the LICENSE.txt file.
# ----------------------------------------------------------------------------
# The following environment variables are required for this process:
# secrets.GH_TOKEN
# secrets.CONDA_UPLOAD_TOKEN_DEV
# secrets.CONDA_UPLOAD_TOKEN_TAG

name: Repo Integration
on: [push]

jobs:

  test:
    name: Test
    runs-on: ubuntu-20.04
    steps:

      # This step checks out a copy of your repository.
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Python Syntax Check
        run: |
          python -m compileall -f python/
          flake8 --count python/

# ----------------------------------------------------------------------------

  gen_release:
    needs: [Test]
    uses: slaclab/ruckus/.github/workflows/gen_release.yml@main
    with:
      version: '1.0.0'
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

# ----------------------------------------------------------------------------

  conda_build_lib:
    needs: [Test]
    uses: slaclab/ruckus/.github/workflows/conda_build_lib.yml@main
    with:
      version: '1.0.0'
    secrets:
      CONDA_UPLOAD_TOKEN_TAG: ${{ secrets.CONDA_UPLOAD_TOKEN_TAG }}

# ----------------------------------------------------------------------------
